"""delete telegram chat

Revision ID: 9da93a8baddc
Revises: d7bf199c7533
Create Date: 2019-02-09 00:47:34.696673

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9da93a8baddc'
down_revision = 'd7bf199c7533'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'userTelegrammChat')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('userTelegrammChat', sa.VARCHAR(length=128), nullable=True))
    # ### end Alembic commands ###
