"""added alarm

Revision ID: d7bf199c7533
Revises: c737cac8c262
Create Date: 2019-02-08 23:22:42.182489

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd7bf199c7533'
down_revision = 'c737cac8c262'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('telegram_chat', sa.Column('alarm', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('telegram_chat', 'alarm')
    # ### end Alembic commands ###
